# This file is part of the Php DDD Standard project.
#
# Copyright (c) 2017-present LIN3S <info@lin3s.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @author Beñat Espiña <benatespina@gmail.com>
# @author Gorka Laucirica <gorka.lauzirika@gmail.com>

app_homepage:
    path: /uploads/
    defaults:
        _controller: "app.http_action.home:__invoke"
    methods:
        - GET

api.files.upload:
    path:  /uploads/files
    defaults:
        _controller: "app.controller.file_controller:uploadAction"
    methods: [ POST ]

api.files.cget:
    path:  /uploads/files
    defaults:
        _controller: "app.controller.file_controller:cgetAction"
    methods: [ GET ]

api.files.get:
    path:  /uploads/files/{file}
    defaults:
        _controller: "app.controller.file_controller:getAction"
    methods: [ GET ]
    requirements:
            file: '\d+'

api.files.download:
    path:  /uploads/files/{file}/download
    defaults:
        _controller: "app.controller.file_controller:downloadAction"
    methods: [ GET ]
    requirements:
            file: '\d+'

api.files.delete:
    path:  /uploads/files/{file}
    defaults: { _controller: RestUploaderBundle:File:delete }
    defaults:
        _controller: "app.controller.file_controller:deleteAction"
    methods: [ DELETE ]
    requirements:
            file: '\d+'